# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2ec7c71cb66270e991ec5c54f417614e75dec00e06e34c11c2d5fe0d915a6352261709a85d3d96b45c1359543fca5ed937f58c5d905317948a400fcac5656fef

test:
  secret_key_base: e561cce1f76635818e3afe44e036560c80d5c26850b0efd5b3bbb9a504275202d13623831f00de676da06d1b9883d28fffc5c3a589648434fac305c83338cdd1

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
